#!/bin/bash

set -e

arg="$1"

if [ -z "$arg" ]; then
    echo "Usage: $0 file.sml" 1>&2
    echo "       $0 file.mlb" 1>&2
    exit 1
fi

set -u

mydir=$(dirname "$0")
. "$mydir/include.sh"

base=$(get_outfile "$arg")

deps="$base".deps

expand_arg "$arg" | fmt -60 | sed 's/^/'"$base"': /'

