#!/bin/bash
#
# mlb-dependencies - read a MLB file defining an SML program and print
# out a list of the files referred to by it and any subsidiary MLB files
#
# Chris Cannam, 2015-2018. MIT licence

set -e

arg="$1"

if [ -z "$arg" ]; then
    echo "Usage: $0 file.mlb" 1>&2
fi

set -u

mydir=$(dirname "$0")
. "$mydir/smlbuild-include.sh"

base=$(get_outfile "$arg")

expand_arg "$arg"

