#!/bin/bash
#
# mlb-dependencies - read a MLB file defining an SML program and print
# out a dependency list in Makefile format
#
# Chris Cannam, 2015-2018. MIT licence

set -e

arg="$1"

if [ -z "$arg" ]; then
    echo "Usage: $0 file.sml" 1>&2
    echo "       $0 file.mlb" 1>&2
    exit 1
fi

set -u

mydir=$(dirname "$0")
. "$mydir/smlbuild-include.sh"

base=$(get_outfile "$arg")

# I wanted to pipe this through fmt, but that turned out to produce
# slightly different results between GNU and BSD (/ Mac) tools and
# resolving the distinction (in order to keep regression tests passing
# across platforms) was too much of a faff for a small aesthetic gain

expand_arg "$arg" | sed 's|^|'"$base"': |'

