#!/bin/bash
#
# polybuild - compile a SML program defined in a MLB file using Poly/ML
#
# Chris Cannam, 2015-2018. MIT licence

set -e

usage() {
    me=$(basename "$0")
    echo "Usage: $me [-o output] file.sml" 1>&2
    echo "       $me [-o output] file.mlb" 1>&2
    exit 1
}

arg="$1"

[ -n "$arg" ] || usage

if [ t"$arg" = "t-o" ]; then
    shift
    out="$1"
    [ -n "$out" ] || usage
    shift
    arg="$1"
    [ -n "$arg" ] || usage
fi

shift
set -u

mydir=$(dirname "$0")

. "$mydir/smlbuild-include.sh"

if [ -z "$out" ]; then
    out=$(get_outfile "$arg")
fi

tmpobj=$(get_tmpobjfile "$arg")

trap "rm -f ${tmpobj}" 0

( expand_arg "$arg" |
	sed 's|^\(.*\)$|use "\1";|' ;            # wrap filenames in REPL use calls
  echo 'PolyML.export("'"$tmpobj"'", main);' ) | # ask poly to export object file
    poly -q --error-exit &&
    polyc -o "$out" "$tmpobj"                    # compile object to executable

