#!/bin/bash

set -e

arg="$1"

if [ -z "$arg" ]; then
    echo "Usage: $0 file.sml" 1>&2
    echo "       $0 file.mlb" 1>&2
    exit 1
fi

set -u

mydir=$(dirname "$0")
. "$mydir/smlbuild-include.sh"

out=$(get_outfile "$arg")

tmpobj="/tmp/obj.$$.o"
tmpout="/tmp/out.$out.$$"
trap "rm -f ${tmpobj} ${tmpout}" 0

( expand_arg "$arg" | \
	sed 's|^\(.*\)$|use "\1";|' ;
  echo 'PolyML.export("'"$tmpobj"'", main);' ) | \
    poly -q --error-exit &&
    polyc -o "$tmpout" "$tmpobj" &&
    "$tmpout" "$@"

