#!/bin/bash

set -e

arg="$1"

if [ -z "$arg" ]; then
    echo "Usage: $0 file.sml" 1>&2
    echo "       $0 file.mlb" 1>&2
    exit 1
fi

set -u

mydir=$(dirname "$0")
. "$mydir/smlbuild-include.sh"

out=$(get_outfile "$arg")  # we don't use this, but it does some arg error checking

rlwrap poly $(expand_arg "$arg" | sed 's/^\(.*\)$/--use \1/')

